### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Jyoti-prakash-rout** [opensourcecommunity-hub/join-the-community#10]
**Name: *Jyoti prakash Rout* 
**Location: *Odisha, India* 
**Interest: *Web dev, IOS dev & DevOps*
**Discord username(optional):- *Jyoti#3098*

### Why do you want to join?
> Looking forward to learning, collaborating & growing as a community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
Welcome to the community!!! Thanks for creating this issue. Invitation has been sent to you. Accept it and make your membership public.
