### ISSUE TITLE
[PROFILE REVIEW]

### ISSUE THREAD

**Issue by Suman373** [opensourcecommunity-hub/join-the-community#101]
### GitHub Profile Link:- 
`https://github.com/suman373`
You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub)

**Comment by Susmita-Dey** [comment]
Hey @Suman373 

Make the following chanegs:
- Add a landscape banner using Canva
- Trophy Count seems broken
- Put the Articles and Blogs section above More Stats section to reach more viewers
- Remove the helpful platform section as it's of no use and seems dummy
- Fix the alignment of Linkedln:
![image](https://user-images.githubusercontent.com/79099734/188910600-1152c774-9f12-406c-a7f2-b4679a6059a0.png)
