### ISSUE TITLE
[PROFILE REVIEW]

### ISSUE THREAD

**Issue by prantikseal** [opensourcecommunity-hub/join-the-community#102]
### GitHub Profile Link:- 
`https://github.com/prantikseal`

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub)

**Comment by Susmita-Dey** [comment]
Hey @prantikseal 

Your profile looks awesome

Improvements:
- Either remove 1 repo or add 1 repo in the pinned section
- When you join an org in future, make it public
- Add the contribution graph generated by GitHub below your README file
