### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by akshitagupta15june** [opensourcecommunity-hub/join-the-community#103]
**Name:**  Akshita Gupta
**Location:** Kanpur
**Interest:** Computer Vision
**Discord username(optional):-** opposite new kesco substation 

### Why do you want to join?
> I want to join to interact with some techy minds 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@akshitagupta15june Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
