### ISSUE TITLE
[PROFILE REVIEW]

### ISSUE THREAD

**Issue by MeghaKeshri** [opensourcecommunity-hub/join-the-community#105]
### GitHub Profile Link:- 
`https://github.com/MeghaKeshri

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub)

**Comment by Susmita-Dey** [comment]
@MeghaKeshri Create a repository with your username and then create a README.md file there which will reflect as your GitHub profile later on after you put something in tht file.
