### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by ravikr126** [opensourcecommunity-hub/join-the-community#107]
**Name:**  Ravi Kumar
**Location:**  Kochi, Kerala , India
**Interest:** MERN development and coding in cpp
**Discord username(optional):-**  Ravi kumar#3187

### Why do you want to join?
> I want to join because learn more about the community and make connections with new techie peoples

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@ravikr126 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
