### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by kalyan-vurugonda** [opensourcecommunity-hub/join-the-community#109]
**Name:** Kalyan Vurugonda
**Location:** Hyderabad
**Interest:** DevOps, Java, Open Source, Community Work
**Discord username(optional):-** Kalyan Vurugonda#0626

### Why do you want to join?
> I want to join because I'm interested in Open Source and Communities and helping and gaining knowledge from the people.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@kalyan-vurugonda Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
