### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by njmsaikat** [opensourcecommunity-hub/join-the-community#110]
**Name:** Saikat Roy
**Location:** Dhaka Bangladesh
**Interest:** Python , Django , Micro-service, Dev Ops
**Discord username(optional):-** njmsaikat

### Why do you want to join?
> I want to join because I want to gain knowledge from experts and share the little I know about stuff. After all that's how we grow as a community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@njmsaikat Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
