### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by aachal28** [opensourcecommunity-hub/join-the-community#114]
**Name:**  aachal pardeshi 
**Location:** Pune,India.
**Interest:** web Development, UI/UX design, App development, Content creation, Art & Design
**Discord username(optional):-** achal#6726

### Why do you want to join?
> I want to join because i want to learn about open source and want to contribute more in open source projects.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@aachal28 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
