### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by ngdream** [opensourcecommunity-hub/join-the-community#115]
**Name:nguewo** 
**Location:cameroon** 
**Interest:gaming**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because 
il love contributing to opensourcde projects and create opensource projects

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@ngdream Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
