### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Vyomrana02** [opensourcecommunity-hub/join-the-community#116]
**Name:**  Vyom Rana
**Location:**  Nadiad
**Interest:** MERN, AI 
**Discord username(optional):-**

### Why do you want to join?
> I want to join because 
TO CONTRIBUTE IN OPENSOURCE.
You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Vyomrana02 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
