### ISSUE TITLE
[ADD ME TO THE ORGANISATION]

### ISSUE THREAD

**Issue by ashavijit** [opensourcecommunity-hub/join-the-community#119]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Susmita-Dey** [comment]
@ashavijit Do you want to join the org or suggest something for the org?

**Comment by ashavijit** [comment]
Yup! can join

**Comment by Susmita-Dey** [comment]
@ashavijit Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
