### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Dynamic00000** [opensourcecommunity-hub/join-the-community#12]
Shweta Tiwari
Pune  
I am interested in Full Stack Development and Java.
**Discord username(optional):-**

### Why do you want to join?
>  I am a beginner in Open Source but I am enthusiastic and eager to learn a lot of things. What else can be better than being in a community of like-minded people? I hope to learn and explore a lot here.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
Thanks for your interest. Invitation have been sent to you. Kindly accept it and make your membership public.
