### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by CodingSpecies** [opensourcecommunity-hub/join-the-community#121]
**Name:** CodingSpecies
**Location:** -
**Interest:** Software Development
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I wish to contribute to this community, not only learn from others, but to help myself.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@CodingSpecies Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
