### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Powerisinschool** [opensourcecommunity-hub/join-the-community#123]
**Name:** Powerisinschool
**Location:** Nigeria
**Interest:** Software Development
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to learn from others and gain skills that will be useful both now and in the future.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Powerisinschool Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
