### ISSUE TITLE
[ADD ME TO THE ORGANIZATION] Please invite me!!!!

### ISSUE THREAD

**Issue by DevStar0202** [opensourcecommunity-hub/join-the-community#125]
**Name:Daivid Morgan
**Location:United States
**Interest:Indoor Tennis
Discord username(optional):-"Devstar0202"

Why do you want to join?
I want to join because

Please invite me to your github group.
Here is Daivid Morgan from Macedonia.
I love teamwork and I really wanna be one of your teammates.

I wanna contribute your github repositories together.

Thanks. Daivid

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@DevStar0202 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
