### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by palak2610** [opensourcecommunity-hub/join-the-community#127]
**Name: Palak Mishra** 
**Location: India** 
**Interest: Open Source Contribution**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I love open source contribution to be a part of a team working in these specific areas. I would love to contribute back to the community. 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@palak2610 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
