### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by 0xMRTT** [opensourcecommunity-hub/join-the-community#128]
**Name:** 0xMRTT	
**Location:** Europe	
**Interest:** Linux GNOME
**Discord username(optional):-**

### Why do you want to join?
> I want to join because i want to join a community of open source guys

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

==> Is there any matrix room ?

**Comment by Susmita-Dey** [comment]
@0xMRTT Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.

But what's matrix room?

**Comment by 0xMRTT** [comment]
Https://matrix.org

**Comment by Susmita-Dey** [comment]
No, there's none
