### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by mehulbaid** [opensourcecommunity-hub/join-the-community#13]
**Name:** Mehul
**Location:** Delhi
**Interest:** MEAN Stack, Cloud Devops, Data Science
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I can be a valuable contributor because of my 5 years of experience in development

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
Thanks for your interest. Invitation have been sent to you. Kindly accept it and make your membership public.
