### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by vaibhavx42** [opensourcecommunity-hub/join-the-community#130]
Name: Vaibhav Bhardwaj
Location: India 
Interest: Open Source Contribution ,Cloud.
Discord username(optional):- Vaibhav

### Why do you want to join?
> I want to join because I love open source contribution to be a part of a team contributing back to community . I would love to be part of such team.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@vaibhavx42 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
