### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by WebSpecialist2021** [opensourcecommunity-hub/join-the-community#133]
**Name: Webdev1025** 
**Location: Internet** 
**Interest: Web Development**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I'd like to learn and contribute myself on this organization.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@WebSpecialist2021 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
