### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [opensourcecommunity-hub/join-the-community#136]
**Name: Sabyasachi Seal** 
**Location: Kolkata, India** 
**Interest: Cloud, DevOps**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because this seems like a good community to be a part of and there are some good people here.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Sabyasachi-Seal Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
