### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by E-fais** [opensourcecommunity-hub/join-the-community#138]
Fais Edathil
Kerala, India
JavaScript and React js
**Discord username(optional):-**

### Why do you want to join?
> I love coding 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@E-fais Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
