### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by randhirshaw** [opensourcecommunity-hub/join-the-community#139]
**Name: Randhir Shaw** 
**Location: Kolkata, India** 
**Interest: Web3, Data Science**
**Discord username(optional):- 𝔇𝑒𝔫𝑣𝔢𝔯#7990**

### Why do you want to join?
> I want to join because I love coding and always keen to upskill and enthusiast of technology.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@randhirshaw Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
