### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by hiiruki** [opensourcecommunity-hub/join-the-community#144]
**Name: Hiiruki** 
**Location: Indonesia** 
**Interest: Jamstack, mobile dev, Cyber Security**
**Discord username(optional): hiiruki#3324**

### Why do you want to join?
> I want to join because I want to contribute to open-source projects

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@hiiruki Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
