### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by GaurabKundu1** [opensourcecommunity-hub/join-the-community#150]
**Name:**  Gaurab Kundu
**Location:** Kolkata, West Bengal, India
**Interest:** Data Science, AI, ML and Development
**Discord username(optional):-** Gaurab01

### Why do you want to join?
> I want to join because 
I would like to contribute and share new ideas with like minded people.
You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@GaurabKundu1 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
