### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by satyamksharma** [opensourcecommunity-hub/join-the-community#152]
**Name: Satyam Kumar** 
**Location: Banglore, India** 
**Interest: Web Development, Frontend, Python**
**Discord username(optional):- Satya#6932**

### Why do you want to join?
> I want to join because i want to get familiar with open source and contribute to projects.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@satyamksharma Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
