### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by dibyarupnath** [opensourcecommunity-hub/join-the-community#153]
**Name: Dibyarup Nath** 
**Location: Kolkata, West Bengal, India** 
**Interest: Python, Machine Learning, SQL, JavaScript**
**Discord username(optional):- DibyarupNath#6099**

### Why do you want to join?
> I want to join because I am new to open source and want to learn more about contributing to it. I have previously completed Hacktoberfest 2022 with 4+ merged PRs.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@dibyarupnath Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
