### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by diva-21** [opensourcecommunity-hub/join-the-community#154]
**Name:Divakar** 
**Location:Hyderabad** 
**Interest:ML,Developmnt,CP**
**Discord username(optional):-**

### Why do you want to join?
> I am eagerly wanted to work with Open Source Communities and contribute my work and upskill my learnings. Wishing to compound more on Learnings with Oragnisation and leveling the insights

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by diva-21** [comment]
Hello there, i didnt got the invitation.
Can you resend it ?

**Comment by Susmita-Dey** [comment]
@diva-21 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.

**Comment by diva-21** [comment]
thank you @Susmita-Dey
