### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Henok-Belachew** [opensourcecommunity-hub/join-the-community#155]
**Name:*Henok Belachew* 
**Location:*Ethiopia* 
**Interest:*Full Stack*
**Discord username(optional):-**

### Why do you want to join?
> I want to join because i'm a full stack student and want to grow my connection and get tips

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Henok-Belachew Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
