### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by SarthakSKumar** [opensourcecommunity-hub/join-the-community#16]
**Name:** Sarthak S Kumar
**Location:** Bangalore, India
**Interest:**Innovation, Web Dev, AI/ML
**Discord username(optional):-**Sarcriticalist#5243

### Why do you want to join?
> I want to join because I want to contribute to open-source and learn from it as well.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@SarthakSKumar Thanks for your interest. Invitation have been sent to you. Kindly accept it and make your membership public.
