### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Omar8345** [opensourcecommunity-hub/join-the-community#17]
**Name:** Omar Moustafa
**Location:** Dubai, UAE
**Interest:** Programming and Gaming
**Discord username(optional):-** Omar Dev 8345#4914 _(Note that I don't open Discord a lot)_

### Why do you want to join?
> I want to join because **I would like to contribute to the open-source community, be part of it, and also encourage people to develop open-source software applications... As I am a advanced programmer I will take a big part of the open-source community, as being a member of the open-source community supports it, each person who is in the open-source community improves the community and encourages everyone! Thank you.**

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Omar8345** [comment]
@Jothin-kumar , are you able to add me?

**Comment by Jothin-kumar** [comment]
> @Jothin-kumar , are you able to add me?

@Omar8345 kindly wait for @Susmita-Dey to add you.

**Comment by Omar8345** [comment]
Okay. Thanks @Jothin-kumar. How you joined the team? Did you apply? _If so, I don't see your issue_ **If not, then, did they personally contact you?!**

**Comment by Jothin-kumar** [comment]
> Okay. Thanks @Jothin-kumar. How you joined the team? Did you apply? _If so, I don't see your issue_ **If not, then, did they personally contact you?!**

@Omar8345 see #2

**Comment by Susmita-Dey** [comment]
@Omar8345 Thanks for your interest. Invitation have been sent to you. Kindly accept it and make your membership public.
