### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by ash56439** [opensourcecommunity-hub/join-the-community#18]
Name:  Ashish Vishwakarma
Location: Lucknow
Interest: Web Development , node.js , C
Discord username(optional):- ash56439

### Why do you want to join?
> I am interested to learn with developer community and helping each other .

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@ash56439 Thanks for your interest. Invitation have been sent to you. Kindly accept it and make your membership public.
