### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by sanjyotpanure** [opensourcecommunity-hub/join-the-community#19]
**Name: Sanjyot Panure** 
**Location: Pune Maharashtra** 
**Interest: Web Technology, Data Science**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to gain some interesting knowledge around and improve my skills.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@sanjyotpanure Thanks for your interest. Invitation have been sent to you. Kindly accept it and make your membership public.
