### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Akshata-Gunapache** [opensourcecommunity-hub/join-the-community#20]
**Name: Akshata Gunapache** 
**Location: Bangalore** 
**Interest: Coding,Collaborating,Partnership**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I would love to share my ideas , learn new things , contribute and develop on my skills.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Akshata-Gunapache Thanks for your interest. Invitation have been sent to you. Kindly accept it and make your membership public.
