### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Neklaustares-tPtwP** [opensourcecommunity-hub/join-the-community#21]
**Name:** Subham Surana
**Location:** India
**Interest:** ML
**Discord username(optional):-** Neklaustares#5626

### Why do you want to join?
> I want to join because I love open-source

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Neklaustares-tPtwP Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
