### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by hashfx** [opensourcecommunity-hub/join-the-community#22]
**Name:** Harsh Soni
**Location:** Indore
**Interest:** WebDev, AndroidDev, DappDev, Open Source
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I'm always open to opportunities and would like to contribute to @opensourcecommunity-hub

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@hashfx  Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
