### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by uday03meh** [opensourcecommunity-hub/join-the-community#23]
**Name:** Uday Mehtani
**Location:** Delhi, India
**Interest:**Web Dev, Python, DSA, Open source
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I am a beginner in open source and want to explore as much communities as possible and contribute to projects. 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@uday03meh Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
