### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by VardaanAggarwal** [opensourcecommunity-hub/join-the-community#24]
**Name:** Vardaan Aggarwal
**Location:** New Delhi, India
**Interest:** Web Development, DevOps, Python and Java Programming. But that's not it I am still exploring things and these interests might change with time.
**Discord username(optional):-** RYUK#3044

### Why do you want to join?
> I want to join because I would love to be a part of this amazing community and contribute to open source, and learn more about it to make valuable contribution in the open source community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@VardaanAggarwal Do you wanna join the organization?

**Comment by VardaanAggarwal** [comment]
@Susmita-Dey Can I get to know about the contributions that I will be making in the community after joining this organisation ?

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey Can I get to know about the contributions that I will be making in the community after joining this organisation ?

You can contribute to other repository and if you're capable to review code and help me then I can make you the maintainer of any of the repos of the organization.

**Comment by VardaanAggarwal** [comment]
> > @Susmita-Dey Can I get to know about the contributions that I will be making in the community after joining this organisation ?
> 
> You can contribute to other repository and if you're capable to review code and help me then I can make you the maintainer of any of the repos of the organization.

That sounds amazing ! I would love be a part of this organisation then, from where can I join ?

**Comment by Susmita-Dey** [comment]
@VardaanAggarwal Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
