### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by DeylerAF** [opensourcecommunity-hub/join-the-community#244]
**Name:** Deyler Alvarez Fernández
**Location:** Costa Rica
**Interest:** Collaborate with the community.
**Discord username(optional):-** DeylerAF#3090

### Why do you want to join?
> I want to join because a want to learn new things and collaborate with the community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@DeylerAF Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
