### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Arjundotadex** [opensourcecommunity-hub/join-the-community#245]
Name: Arjun
Location: New Delhi, India
Interest: Coding
Discord username(optional):- A R J U N#9922

### Why do you want to join?
> I want to join because I want to make new connections and want to contribute. Being an Open Source contributor and being a part of the Devs-in-tech community will allow me to contribute to various projects.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Arjundotadex Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
