### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by SubhamSaha99** [opensourcecommunity-hub/join-the-community#246]
**Name: Subham Saha
**Location: West Bengal
**Interest: Web dev
**Discord username(optional): - 𝙁𝘼𝙇𝙇𝙀𝙉𝘾𝘼𝙋#9407

### Why do you want to join?
> I want to join because I want to contribute in open-source

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@FallenCap Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
