### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Sinrez** [opensourcecommunity-hub/join-the-community#248]
**Name:**  Alex
**Location:**  Russia
**Interest:** technologies and science
**Discord username(optional):-** I don't use discord

### Why do you want to join?
Hello.
I am interested in new technologies and language.
I am currently learning Python.
This project is interesting for my self-education

Thank you for the opportunity

Regards, Alex

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Sinrez Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
