### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by pshri5** [opensourcecommunity-hub/join-the-community#249]
**Name: Preetam** 
**Location: India** 
**Interest: Web development**
**Discord username(optional):- FruitpunchSamurai**

### Why do you want to join?
> I want to join because I want to get better at web development by collaborating with others in the open-source community and adding value to the community 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@pshri5 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
