### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by gawadeatul** [opensourcecommunity-hub/join-the-community#250]
**Name: Atul N Gawade**
**Location: Mumbai, India** 
**Interest: Backend Development | DevOps**
**Discord username(optional):- atulgawade#3867**

### Why do you want to join?
 I want to join because want to get started with open-source and contribute.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@gawadeatul Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
