### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by iriteshmishra** [opensourcecommunity-hub/join-the-community#251]
**Name: Ritesh Mishra** 
**Location: Mumbai** 
**Interest: coding and creating websites**
**Discord username(optional):-**

### Why do you want to join?
> I want to join the community because I want to start contributing to open source projects.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@iriteshmishra Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
