### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by hs7898753** [opensourcecommunity-hub/join-the-community#252]
Name: Harsh Sharma
Location: Bhopal, India
Interest: Competetive Programmer,  Web Development, ROS.
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to get started with my Open-Source journey.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@hs7898753 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
