### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Ahtaxam** [opensourcecommunity-hub/join-the-community#256]
**Name:**  Ahtasham ALi
**Location:**  lahore , Pakistan
**Interest:** Web Development ,  javaScript
**Discord username(optional):-** Ahtasham#4470

### Why do you want to join?
I want to join because i want to collaboarte with develoers from all over world and want to learn from others

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Ahtaxam Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
