### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Gaurav560** [opensourcecommunity-hub/join-the-community#259]
Name:Gaurav Sharma
Location:Chandigarh,India
Interest:Java Full Stack Web Application Developement ,Open Source,Cloud,Docker and Kubernetes
Discord username(optional):-gaurav6031#1181

 Why do you want to join?
> I want to join because  i want to learn about Open Source, How to contribute to Open Source , make projects ,learn Cloud ,Docker and Kubernetes.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Gaurav560 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
