### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by vedprakashnautiyal** [opensourcecommunity-hub/join-the-community#260]
**Name:** Ved Prakash Nautiyal
**Location:** Dehradun
**Interest:** ML , Robotics & Cloud
**Discord username(optional):-** vedprakashnautiyal#4423

### Why do you want to join?
> I want to join because I have been following the works of many people in this community & I want to connect with more such like minded people and contribute & add value in any way I can. I feel that being part of this github community will also allow me to observe the work of members more closely and learn,

**Comment by Susmita-Dey** [comment]
@vedprakashnautiyal Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
