### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Mayank-Sharma17** [opensourcecommunity-hub/join-the-community#261]
**Name:** Mayank Sharma 
**Location:** Uttarakhand, India
**Interest:** Web Development, **DevOps**
**Discord username(optional):-** Mynkscord#3535

### Why do you want to join?
> I want to join DevsInTech community to learn and collaborate with others, I participated in MLH GHW API week and joined this community as my guild so it's really a good opportunity for me to be a part of the organization and collaborate on different upcoming projects.
I already joined the discord community <3.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Mayank-Sharma17 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
