### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by quantavoid11** [opensourcecommunity-hub/join-the-community#262]
**Name:** Siddhant Kumar Keshri
**Location:** New Delhi, India
**Interest:**Web Development, DSA, ML/AI, DevOps, Gaming.
**Discord username(optional):-**Siddhant_keshri#1145

### Why do you want to join?
> I want to join because it is a good community from which I can learn a lot of things, expand my knowledge, and share it with others to help overall growth in the community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@quantavoid11 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
