### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by noobyco** [opensourcecommunity-hub/join-the-community#263]
**Name: Md Moinuddin** 
**Location: India** 
**Interest: Web development, technical writing, Iot**
**Discord username(optional):- Noobyco#1061**

### Why do you want to join?
> I want to join because i love collaborating with awesome tech people to work ogethen on single project.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Blaize15 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
