### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by gambhirsharma** [opensourcecommunity-hub/join-the-community#266]
**Name: Gambhir Sharma** 
**Location: India** 
**Interest: Web-Development, Machine Learning and Technical blog**
**Discord username(optional):- Gambhir_Sharma#8276**

### Why do you want to join?
> I want to join this community because I want to grow my network and learn new things.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@gambhirsharma Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
