### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by omlondhe** [opensourcecommunity-hub/join-the-community#267]
**Name:** Om Prashant Londhe
**Location:** Aurangabad
**Interest:** Full-Stack Development
**Discord username(optional):-** Om2133#1476

### Why do you want to join?
> I want to join because I want to be a remote full-stack developer

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@omlondhe Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
