### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by mhdamaan79** [opensourcecommunity-hub/join-the-community#268]
**Name: Mohd Amaan** 
**Location: India** 
**Interest: Web Development, Data Structures & Algorithms & Open Source**

### Why do you want to join?
> I want to join because it'll help me to connect with industry experts, learn about new technologies, contribute to open-source projects, and help others by sharing my knowledge and expertise.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@mhdamaan79 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
