### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Hrithik5** [opensourcecommunity-hub/join-the-community#269]
**Name:** Hrithik Chauhan
**Location:** India
**Interest:** Backend Development and System Design
**Discord username(optional):-** hrithikchauhan#2205

### Why do you want to join?
> I want to join because I would love to contribute to projects and network will new peoples

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Hrithik5 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
