### ISSUE TITLE
[PROFILE REVIEW]

### ISSUE THREAD

**Issue by Mohamed-AH** [opensourcecommunity-hub/join-the-community#27]
### GitHub Profile Link:- 
`https://github.com/Mohamed-AH`

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub)

**Comment by Susmita-Dey** [comment]
Hey @Mohamed-AH 

Few improvements are needed as follows -

1. You can write a little more in your About Me Section
2. You're duplicating your projects by adding it in the README as you have already added in the pinned section and things don't like too good in the way.
3.  I think you're using light mode but things don't look good in dark mode.
Example - 
![image](https://user-images.githubusercontent.com/79099734/188901585-5e47bbed-1568-4bbf-8e91-ca0949684883.png)

Other things are okay for now.

**Comment by Mohamed-AH** [comment]
thanks for the feedback, it looks awful in dark mode. i ll change it .
