### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by aashay28** [opensourcecommunity-hub/join-the-community#270]
**Name:** aashay28
**Location:** India
**Interest:** Frontend, development, collaboration
**Discord username(optional):-**

### Why do you want to join?
> I am excited to join this community because it seems like a welcoming and supportive group of people who share common interests and values. I am eager to learn from others and contribute my own knowledge and experience.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@aashay28 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
