### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by priyazsh** [opensourcecommunity-hub/join-the-community#271]
**Name:** Priyansh
**Location:** india
**Interest:** web development
**Discord:** Priyansh#5220
### Why do you want to join?
> I want to join because i like to collabrate

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@oyepriyansh Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
