### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by MehraDevesh2022** [opensourcecommunity-hub/join-the-community#275]
**Devesh Mehra:** 
**Uttarakhand** 
**MERN stack development , core java , c , SQL , open source , anime:**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because 
I want to join this community because I am passionate about open source and computer science. I like that this community is collaborative, supportive, and diverse. I think I can learn a lot from the other members and also contribute to the projects and initiatives of the community. I believe that open source is the future of software development and I want to be part of it.
You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by MehraDevesh2022** [comment]
close this

**Comment by Susmita-Dey** [comment]
@MehraDevesh2022 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
