### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by roy2pushkar** [opensourcecommunity-hub/join-the-community#277]
**Pushkar Roy** 
**Bhopal:** 
**Full stack Developer:**
**Discord username(optional):-**

### Why do you want to join?
>  Here I come to join for learn and grow together . Community is best way to learn new technologies and for land in open source . I eagerly waiting for give contribution to community .

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@roy2pushkar Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
