### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Shalini469717** [opensourcecommunity-hub/join-the-community#278]
**Name:** Shalini Muskula
**Location:** India
**Interest:** Web Development

### Why do you want to join?
> I want to join because I want to learn and grow together with other people in the community.

**Comment by Susmita-Dey** [comment]
@Shalini469717 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.

**Comment by Shalini469717** [comment]
> @Shalini469717 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
> 
> 

Sure thank you!
