### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Parth0x108** [opensourcecommunity-hub/join-the-community#280]
**Name: Parth Mandale** 
**Location: Pune, Maharashtra** 
**Interest: Web Development, Open Source, web3**
**Discord username(optional):- Parth Mandale#8947**

### Why do you want to join?
> I want to join because I want to connect with like-minded people in tech and want to build a network where I can learn and grow together in open source community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Parth0x108** [comment]
@Susmita-Dey Please review my PR and Invitation.

**Comment by Susmita-Dey** [comment]
@Parthmandale Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
