### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by chloe-valentine** [opensourcecommunity-hub/join-the-community#284]
**Name:** Aisling Sheridan
**Location:** Ireland 
**Interest:** HTML, CSS, Javascript // product management // cybersecurity 
**Discord username(optional):-** 

### Why do you want to join?
> I want to join because I want to collab with other dev techs and see what kind of projects other people are making. 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@chloe-valentine  Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.

**Comment by chloe-valentine** [comment]
Thank you for accepting my invitation Susmita-Dey!
