### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by AnuragRoy485** [opensourcecommunity-hub/join-the-community#285]
**Name:** Anurag Roy
**Location:** India
**Interest:**Coding
**Discord username(optional):-**- A N U R A G ✨#8112

### Why do you want to join?
> I want to join because I love joining communities

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@AnuragRoy485 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
