### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by CBID2** [opensourcecommunity-hub/join-the-community#286]
**Name:** Christine 
**Location:** N/A
**Interest:** Open Source
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to grow as a Open Source maintainer

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@CBID2 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.

**Comment by CBID2** [comment]
> @CBID2 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
> 
> 
> 
> 

Thank you! :)
