### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by anshul-kh** [opensourcecommunity-hub/join-the-community#287]
**Name:** Anshul 
**Location:** India 
**Interest:** Open Source, DevOps
**Discord username(optional):-**

### Why do you want to join?
> I want to join because 
I want to join this org to connect with others and learn,share experiences with them.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@anshul-kh  Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
