### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by julycrystal** [opensourcecommunity-hub/join-the-community#289]
**Name:** Erik Xin
**Location:** Stockholm, Sweden
**Interest:** Python, AI
**Discord username(optional):-** erikxins#1205

### Why do you want to join?
> I would like to be a part of this org.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@julycrystal  Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
