### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by munnokd** [opensourcecommunity-hub/join-the-community#291]
**Name: Kalp Prajapati** 
**Location: Ahmedabad India** 
**Interest: Software development and open source **
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I found this community works well and there are some good projects where I wanted to contribute.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@munnokd  Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
