### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by rakeshbabu23** [opensourcecommunity-hub/join-the-community#293]
Name:Rakesh Babu
**Location:Dharmavaram,India
**Interest:Web development
**Discord username(optional):-rakesh#7102

### Why do you want to join?
> I want to join because, I am new to open source. I would like increase my network, learn from them and I love collaboration.
I like to improve myself by learning skills.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@rakeshbabu23 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
