### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by kunal-halder577** [opensourcecommunity-hub/join-the-community#294]
**Name:**  Kunal Halder 
**Location:**  Kolkata 
**Interest:** Development/DevOps
**Discord username(optional):-** iamKunal_26

### Why do you want to join?
> I want to join because i want to contribute to open source and gain real world work expirence. I want to know how things are being done in the industry. Want to meet new people, connect with them & work with them. And also to grow my network.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@kunal-halder577 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
