### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [opensourcecommunity-hub/join-the-community#295]
**Name: Shiva Sai
**Location: India
**Interest: Web Development
**Discord username(optional):-**

### Why do you want to join?
> I want to join to grow my network and contribute to open source projects.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Shiva-Sai-ssb Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
