### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by GreatSuperstar** [opensourcecommunity-hub/join-the-community#299]
**Name:SkyCaptainess** 
**Location:USA** 
**Interest:Coding**
**Discord username(optional):-AC#2873**

### Why do you want to join?
> I want to join because I am looking for my friend.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@GreatSuperstar Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
