### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by tanmaycode2** [opensourcecommunity-hub/join-the-community#3]
**Name: Tanmay shukla** 
**Location: Jaipur** 
**Interest: Python, Java and Cloud computing**
**Discord username(optional):- tanmaydisc#8979**

### Why do you want to join?
> I want to join because I wanted to learn to contribute to open source as I am currently in early phase of my programming and open source journey. I feel that contributing and learning on the go is the best way to be relevant as a developer.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
Good to know about you. Thanks for opening this issue. I've sent the invitation to you to join the community. Kindly accept it and make your membership public.
