### ISSUE TITLE
[PROFILE REVIEW] - Murtuza

### ISSUE THREAD

**Issue by murtuzaalisurti** [opensourcecommunity-hub/join-the-community#30]
### GitHub Profile Link:- 
`https://github.com/murtuzaalisurti`

**Comment by Susmita-Dey** [comment]
Hey @murtuzaalisurti 

Your profile looks good. 

You can make the following improvements-
- Add a banner at the top
- Languages you've worked with and the tech stack seems both duplicate. So, I'd recommend you to keep only one of them.
- Keep the latest blog posts section at the top or in the middle if you wanna catch more viewers.
