### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by omk-coder** [opensourcecommunity-hub/join-the-community#301]
Name: Omkar Ramishte
Location: India
Interest: Designing, coding, blog writing.
Discord username(optional):-omkar#1549

### Why do you want to join?
> I am already member of this community server. this community helps in many ways for helping contribution of open source project to upskilling as  well through blogging challenges.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@omk-coder Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
