### ISSUE TITLE
[i want to Be A Member of this community]

### ISSUE THREAD

**Issue by OwaisAzad** [opensourcecommunity-hub/join-the-community#302]
**Name:*Owais Azad* 
**Location:*Karachi, Pakistan* 
**Interest:*DataOps*
**Discord username(optional):-**

### Why do you want to join?
> I want to join this community because there are lots of people, and I am sure I will learn here.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@OwaisAzad  Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
