### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by captainWaheed** [opensourcecommunity-hub/join-the-community#303]
**Name: Abdul Waheed** 
**Location: Pakistan** 
**Interest: Open source contributions**

### Why do you want to join?
> I want to join because I believe joining the community will provide me an opportunity to contribute, collaborate with like-minded individuals, and learn from their expertise.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@captainWaheed  Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
