### ISSUE TITLE
[I want to join this group]

### ISSUE THREAD

**Issue by VikingDDM** [opensourcecommunity-hub/join-the-community#304]
**Name:**  VikingDDM
**Location:**  Sweden
**Interest:**  Architecture
**Discord username(optional):-**  

### Why do you want to join?
> I want to join because I want to learn many things and share experience.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@VikingDDM  Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
