### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by vishnu9865** [opensourcecommunity-hub/join-the-community#307]
**Name:** Jeyavishnu S
**Location:** Coimbatore, TN, India
**Interest:** Full Stack Web Development and Mobile Development
**Discord username(optional):-** Jeyavishnu S#2211

### Why do you want to join?
> I want to join your community to contribute and learn as well as help others through guidance and support to the best of my abilities.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@vishnu9865  Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
