### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by hasegawa0x3** [opensourcecommunity-hub/join-the-community#308]
**fancyKing0714:** 
**Ukraine:** 
**Web development:**
**Sept Wolf#0321**

### Why do you want to join?
> I want to join because I am a full stack developer with high skills and rich experience in MEVN stack.

**Comment by hasegawa0x3** [comment]
thanks.

**Comment by Susmita-Dey** [comment]
@FancyKing0714  Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
