### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by eKeiran** [opensourcecommunity-hub/join-the-community#309]
**Name:Keera** 
**Location:Pune, India** 
**Interest: Front-end Web Dev and Linux Kernels**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because this seems like a fun way to contribute and get to know people!

**Comment by Susmita-Dey** [comment]
@eKeiran  Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
