### ISSUE TITLE
[PROFILE REVIEW]

### ISSUE THREAD

**Issue by vquiah** [opensourcecommunity-hub/join-the-community#31]
### GitHub Profile Link:- 
`https://github.com/<vquiah>`

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub)

**Comment by Susmita-Dey** [comment]
Hey @vquiah 

Make the following changes:
- GitHub profile README should be a little longer. 
- Banner and social logos in center
- Remove the `#` in the headline before `Hi`
