### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by biswajit-k** [opensourcecommunity-hub/join-the-community#312]
**Name:** Biswajit Kaushik
**Location:** India
**Interest:** Open-Source development in Python
**Discord username(optional):-** Biswajit_Kaushik#1795

### Why do you want to join?
> I want to join because I like the initiative this community is taking towards promoting open-source and educating people around the world to contribute to open-source. This makes me highly excited and willing to join this awesome community so that I can also learn and grow together with everyone.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@biswajit-k  Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
