### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by dave-ad** [opensourcecommunity-hub/join-the-community#315]
**David:** 
**Nigeria:** 
**Software engineering:**
**Discord username(Tibol):-**

### Why do you want to join?
> I want to join so I can grow as a software engineer 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@dave-ad Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
