### ISSUE TITLE
I want to work in this organization.

### ISSUE THREAD

**Issue by HappyMicky0317** [opensourcecommunity-hub/join-the-community#317]
**Name:** 
**Location:** 
**Interest:**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
Hi,we're not hiring any volunteers right now. You may join us in Discord to be part of the community.
