### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by AyushDey** [opensourcecommunity-hub/join-the-community#319]
**Name: *Ayush Dey* 
**Location:*Howrah* 
**Interest:*GitHub, Open Source*
**Discord username(optional):-*abstractdreamer*

### Why do you want to join?
> I want to join because I want to learn and be proficient about how to work with GitHub and also gather knowledge about how to work in Open Source

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@AyushDey Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
