### ISSUE TITLE
[PROFILE REVIEW]

### ISSUE THREAD

**Issue by playatanu** [opensourcecommunity-hub/join-the-community#32]
### GitHub Profile Link:- 
`https://github.com/playatanu`

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub)

**Comment by Susmita-Dey** [comment]
Hey @playatanu 
Your profile looks awesome as it's clean and short

One improvement you should do is add one repo in the pinned projects section to hide the blank extra space or you can keep 4 pinned projects there.
