### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by vijay2249** [opensourcecommunity-hub/join-the-community#323]
**Name:** Vijay CN
**Location:** Online
**Interest:** Web Dev | Python Developer | Linux | Networking
**Discord username(optional):-** 

### Why do you want to join?
> I want to join because learn and supply the material that i have learned so far and yet to learn stuff. (also to meet some cool people😜)

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@vijay2249 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
