### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by vivekrawat21** [opensourcecommunity-hub/join-the-community#324]
**Name:** Vivek Rawat
**Location:**  India ,Uttarakhand
**Interest:** Java Devlopment || WebDevlopment
**Discord username(optional):-**

### Why do you want to join?
> I want to join because i want to learn new stuffs which will help me to grow as individual 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@vivekrawat21 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
