### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by alimalim77** [opensourcecommunity-hub/join-the-community#325]
**Name: Mohammad Alim** 
**Location: Kanpur, India** 
**Interest: Web Development, Python, Technical Writing**
**Discord username(optional):- alimmo**

### Why do you want to join?
> I want to join because I have been exploring open source and love to see the helpful community and numerous learning opportunities. I have done internships in software domain and mentored countless students over the last two years. and this is a new yet interesting challenge for me.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@alimalim77 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
