### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by dhruvdabhi101** [opensourcecommunity-hub/join-the-community#326]
**Name:**  Dhruv Dabhi
**Location:**  Gujarat, India
**Interest:**  Web3 Development, Full Stack Development
**Discord username(optional):-** dhruvdabhi#0001

### Why do you want to join?
> I want to join because 
I want to collaborate more in open source

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@dhruvdabhi101 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
