### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by panda0125** [opensourcecommunity-hub/join-the-community#328]
**Name:Liam Rodrigues** 
**Location: Canada** 
**Interest: Fullstack, Blockchain, **
**Discord username(optional):-snowman8831**

### Why do you want to join?
> I want to join because I am a senior fullstack blockchain developer

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@panda0125 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
