### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by whoisjayd** [opensourcecommunity-hub/join-the-community#329]
**Name:** Jaydeep Solanki
**Location:** India
**Interest:** Python, NextJs, PyQT
**Discord username(optional):-** jay.deep

### Why do you want to join?
> I want to join because to enhance my knowledge and work as team

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@WhoIsJayD Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
