### ISSUE TITLE
[PROFILE REVIEW]

### ISSUE THREAD

**Issue by ozboware** [opensourcecommunity-hub/join-the-community#33]
### GitHub Profile Link:- 
`https://github.com/ozboware`

**Comment by Susmita-Dey** [comment]
Hey @ozboware 

Make the following changes to your profile:
- README file is too long; make it shorter
- Add your projects in the pinned repo section and remove the screenshots to make it look good
- An about section and a banner at the top is recommended

💡 Tip: Don't follow so many `3.6k` people. It's a lot.
