### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [opensourcecommunity-hub/join-the-community#330]
**Name:** Saptarshi Sarkar
**Location:** India
**Interest:** Open-Source software development
**Discord username(optional):-** saptarshisarkar

### Why do you want to join?
> I want to join because I want to connect with new peoples in the community, help others and learn new things from the community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@SaptarshiSarkar12 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.

Done 👍. Thank you @Susmita-Dey !
