### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Petsamuel** [opensourcecommunity-hub/join-the-community#332]
**Name:** **Samuel Peters**
**Location:** West Africa
**Interest:** Contributor/Reviewer
**Discord username(optional):-** bieefilled#5583

### Why do you want to join?
> I want to join because i'm an open-source enthusiast. 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Petsamuel Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
