### ISSUE TITLE
[PROFILE REVIEW]

### ISSUE THREAD

**Issue by pratik2315** [opensourcecommunity-hub/join-the-community#34]
### GitHub Profile Link:- 
`https://github.com/pratik2315`

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub)

**Comment by Susmita-Dey** [comment]
Hey @pratik2315 

Make the following improvements -
- About Us section and a Banner at the top
- This seems broken; fix it
![image](https://user-images.githubusercontent.com/79099734/188907432-02da1539-e355-495f-a405-9de803eba545.png)
