### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by MizouziE** [opensourcecommunity-hub/join-the-community#35]
**Name:** 
Sam

**Location:** 
Spain (Although I am British)

**Interest:**
PHP, Laravel but I'll try anything if it's open source

### Why do you want to join?
> I want to join because I started a project that was aiming to help beginners get into open source and it turned into something amazing within a week. It has shown me how incredible this community can be and I would like to start more projects with a similar target.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@MizouziE It's great to hear about your project. Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
