### ISSUE TITLE
[PROFILE REVIEW]

### ISSUE THREAD

**Issue by MizouziE** [opensourcecommunity-hub/join-the-community#36]
### GitHub Profile Link:- 
[MizouziE](https://github.com/MizouziE)

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub)

**Comment by Susmita-Dey** [comment]
Hey @MizouziE 

Make the following changes:
- Remove the code and write your bio in simple English language
- Add a repo in your pinned repos section
- Align stats cards side by side
- Focus a little more on code reviews
