### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by sakethpathike** [opensourcecommunity-hub/join-the-community#37]
**Name: Saketh** 
**Location: Hyderabad, India** 
**Interest: Android DevelopmentAnd Backend Stuff!**
**Discord username(optional):-**

### Why do you want to join?
> I'm new to these and want to check out how it means to be in an open-source community:)

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@sakethpathike Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
