### ISSUE TITLE
[PROFILE REVIEW]

### ISSUE THREAD

**Issue by mayankkuamr001** [opensourcecommunity-hub/join-the-community#38]
### GitHub Profile Link:- 
`https://github.com/mayankkuamr001`

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub)

**Comment by Susmita-Dey** [comment]
Hey @mayankkuamr001 
Your profile is short and clean. 

If you want you can always modify it but for now its okay.

Improvement:
- Add your socials 
- Add 1 more pinned repo to remove extra spaces
- Focus a little more on code reviews
