### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by at-the-vr** [opensourcecommunity-hub/join-the-community#386]
**Name:** Atharva
**Location:** India
**Interest:** Documentation
**Discord username(optional):-** itseobard

### Why do you want to join?
> Passionate for Documentation, enjoy my time around frameworks, love to receive feedback for my stuff

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by 1we34rrt6** [comment]
saitaldoghmy369@gmail.com

**Comment by 1we34rrt6** [comment]
https://www.facebook.com/almorjan.saleh?mibextid=ZbWKwL

**Comment by 1we34rrt6** [comment]
https://www.facebook.com/almorjan.saleh?mibextid=ZbWKwL
