### ISSUE TITLE
[PROFILE REVIEW]

### ISSUE THREAD

**Issue by Shivam-Katare** [opensourcecommunity-hub/join-the-community#39]
### GitHub Profile Link:- 
`https://github.com/Shivam-Katare`

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub)

**Comment by Susmita-Dey** [comment]
Hello @Shivam-Katare 

Improvements to be done:
- Add a banner
- Center the tech stack and socials
- Align the GitHub Stats side by side
