### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [opensourcecommunity-hub/join-the-community#41]
**Name: Mohammed Ehab** 
**Location: Egypt** 
**Interest: Coding**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to contribute to more projects and Build your templates page

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Programming-School-Pro-Coding Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
