### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Yuval207** [opensourcecommunity-hub/join-the-community#43]
**Name:** Yuval Sharma
**Location:** Delhi, India
**Interest:**Web development, Open source, Linux and Devops
**Discord username(optional):-**Yuval1207#4857

### Why do you want to join?
> I want to join because I am looking forward to contribute to these awesome communities and gain some experience about open source. As a beginner this would help me in building my profile and also contribute to this community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Yuval207 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
