### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by GAbdulwhb** [opensourcecommunity-hub/join-the-community#48]
**Name:** Ghada AbdulWahab
**Location:**  Egypt
**Interest:** web Development anddata analysis 
**Discord username(optional):-**Ghada#6501

### Why do you want to join?
> I want to join because I am interested in open source projects and want  to contribute to other people from overall the world

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@GAbdulwhb Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
