### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Bhuvanesh1006** [opensourcecommunity-hub/join-the-community#5]
**Name: Bhuvanesh d
**Location: Chennal,india
**Interest: Python,HTML and CSS
**Discord username(optional):-Bhuvanesh Dev#7551

### Why do you want to join?
> I want to join because I'm very keen and intrested to contribute to open source in any way possible and add value.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
Good to know about you. Thanks for opening this issue. I've sent the invitation to you to join the community. Kindly accept it and make your membership public.
