### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by arth2002** [opensourcecommunity-hub/join-the-community#50]
**Name: Arth Prajapati** 
**Location: India** 
**Interest: Open-Source, Competitive Programming, DevOps**
**Discord username(optional):-User64bit#9400**

### Why do you want to join?
> I want to join because I want to contribute to Open-Source Community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@arth2002 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
