### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Akash-S1999** [opensourcecommunity-hub/join-the-community#51]
**Name: Akash Singh** 
**Location: Kolkata** 
**Interest: Web Development/React**
**Discord username(optional):- imakashsingh**

### Why do you want to join?
> I want to join because I want to contribute to the open-source community and also learn through the exposure that I will get by joining the community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Akash-S1999 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
