### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by HarshitRV** [opensourcecommunity-hub/join-the-community#52]
**Name: Harshit Kr Vishwakarma** 
**Location: Varanasi, Uttar Pradesh** 
**Interest: Backend Web Devlopment (Node.js)**
**Discord username(optional):- WOLVERINE911#3940**

### Why do you want to join?
> I want to join because I want to learn and learning is more fun by working on projects and collaborating with like-minded people. 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@HarshitRV Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
