### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by thuongtruong1009** [opensourcecommunity-hub/join-the-community#54]
**Name: Tran Nguyen Thuong Truong
**Location: VietNam
**Interest: Coding and explore trick, music
**Discord username(optional): thuongtruong1009

### Why do you want to join?
> I want to join because I learned about your organization is the best community for me. I want to learn more and more about open-source code and wish to cooperate with friends worldwide!

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@thuongtruong1009 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
