### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by JayantGoel001** [opensourcecommunity-hub/join-the-community#55]
**Name:** Jayant Goel
**Location:** India
**Interest:** Web Development
**Discord username(optional):-** JayantGooel001

### Why do you want to join?
> I want to join because I want to contribute to Open-Source Community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@JayantGoel001 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
