### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by kum9748ar** [opensourcecommunity-hub/join-the-community#56]
**Name:**  Kumar Kalyan
**Location:** Kolkata  India 
**Interest:** Web dev
**Discord username(optional):-** kumar#6533

### Why do you want to join?
> I want to join for adding some valuable contributions to this community 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@kum9748ar Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
