### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by KUSHAGRA-JAISWAL** [opensourcecommunity-hub/join-the-community#57]
**Name: KUSHAGRA JAISWAL** 
**Location:  VARANASI** 
**Interest: OpenSource WebDev**
**Discord username(optional):- ƙųʂɧ#8651**

### Why do you want to join?
> I want to join because I want to learn and improve my skills in WebDev and also to learn how to contribute to OpenSource. 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@KUSHAGRA-JAISWAL Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
