### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by ianskie26** [opensourcecommunity-hub/join-the-community#58]
**Name:** Ian Luciano
**Location:** Philippines
**Interest:** Open Source, Web Development
**Discord username(optional):-** zero73#8210

### Why do you want to join?
> I want to join because I want to be part and contribute to an open source community

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@ianskie26 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
