### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by shashankbhatgs** [opensourcecommunity-hub/join-the-community#6]
**Shashank Bhat G S**
**India** 
**Open-source, DSA, Cloud, Web-development**
**Shashank#4240**

### Why do you want to join?
> I want to join because, this community is inclusive and I want to learn, contribute and collaborate!

**Comment by Susmita-Dey** [comment]
Welcome to the community!!! Thanks for creating this issue. Invitation has been sent to you. Accept it and make your membership public.
