### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Estevamsl** [opensourcecommunity-hub/join-the-community#61]
**Name:**
- Estevamsl

**Location:**
- Brazil

**Interest:**
- Nest -> Server-side

**Discord username(optional):-**

### Why do you want to join?
> I want to join because 

Because I want to stay on top of everything that goes on in this organization and of course, as a good dev, you have to know about the challenges of this incredible world of programming

**Comment by Susmita-Dey** [comment]
@Estevamsl Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
