### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Islam-Youssief** [opensourcecommunity-hub/join-the-community#64]
**Name:** Islam Youssief
**Location:** Egypt
**Interest:** I love Open Source community 
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I am a senior software engineer and I want to participate and cooperate with others also I love open source community and want to learn more and help the community to rise 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Islam-Youssief Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
