### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by AvidCoder101** [opensourcecommunity-hub/join-the-community#67]
AvidCoder
Living in the Github World
React, Node, HTML, JS, CSS
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I love contributing to other orgs and repos and developing my coding skills

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@AvidCoder101 I have already invited you.
