### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by SimonBaey** [opensourcecommunity-hub/join-the-community#68]
**Name:** SimonBaey
**Location:** Canada
**Interest:**Full Stack
**Discord username(optional):-**

### Why do you want to join?
> I want to join because 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@SimonBaey Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
