### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by bishtanuj** [opensourcecommunity-hub/join-the-community#69]
**Name: ANUJ BISHT** 
**Location: DELHI, INDIA** 
**Interest: Open Source, Data Structure and Algorithms, Web Development, Software Development**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I find this community amazing, that encourage the open source among the tech savvy around the world. I would like to learn from the community, and also wants to contribute when required. Hope you will get me in!

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by bishtanuj** [comment]
Didn't get link to join the community!

**Comment by Susmita-Dey** [comment]
@bishtanuj Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
