### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by AjRadwan** [opensourcecommunity-hub/join-the-community#7]
**Radwan:** 
**Bangladeshs:** 
**Web Devlopment:**
**Anowar J Radwan:-**

### Why do you want to join?
> I want to join because  I want to learn more and contribute to open source and  interact with fellow peers from all over the globe

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
Welcome to the community!!! Thanks for creating this issue. Invitation has been sent to you. Accept it and make your membership public.
