### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by theashishgavade** [opensourcecommunity-hub/join-the-community#70]
**Name:** theashishgavade
**Location:** India
**Interest:** Software Development 
**Discord username:-** theashishgavade

### Why do you want to join?
> I want to join because 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@theashishgavade Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
