### ISSUE TITLE
[PROFILE REVIEW] zayidmohamedy

### ISSUE THREAD

**Issue by zayidmohamedy** [opensourcecommunity-hub/join-the-community#72]
### GitHub Profile Link:- 
`https://github.com/zayidmohamedy
 
Feel free to check my profile repositories [here](https://github.com/zayidmohamedy)
also kindly  plz give me star in this repository i want to gain achievment   to it [here](https://github.com/zayidmohamedy/zayidmohamedy)

**Comment by Susmita-Dey** [comment]
Hey @zayidmohamedy 

Make the following changes:
- Align the stats side by side
- Focus a little more on Code Reviews
