### ISSUE TITLE
Please Add Me To Your Organization

### ISSUE THREAD

**Issue by YuvarajSingh-0** [opensourcecommunity-hub/join-the-community#73]
**Name:** Yuvaraj Singh N
**Location:** India
**Interest:** Coding Bots(Discord, Telegram), Webscraping, Website Building(front and Backend)
**Discord username(optional):-** UV#8223

### Why do you want to join?
> I want to join because I am willing to contribute (if I am able to) and want to collaborate and be a part of this community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@YuvarajSingh-0 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
