### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by cixtor** [opensourcecommunity-hub/join-the-community#76]
**Name:** cixtor
**Location:** Earth
**Interest:** System Engineering
**Discord username(optional):** cixtor

### Why do you want to join?

I want to join because I have been an active member of the open-source community on GitHub and other platforms, and it is always a joy to find like-minded people willing to share knowledge and experiences. I would love to join thir GitHub organization to help many more developers become excellent open-source maintainers.

**Comment by Susmita-Dey** [comment]
@cixtor Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
