### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by susheelpal** [opensourcecommunity-hub/join-the-community#8]
**Name:**  Susheel Pal
**Location:** Bangalore, India
**Interest:** DevOps Engineer tools and related language
**Discord username(optional):-** susheelpal#2472

### Why do you want to join?
> I want to join because I want to contribute in open source and want to learn in public.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
Welcome to the community!!! Thanks for creating this issue. Invitation has been sent to you. Accept it and make your membership public.
