### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by imhunterand** [opensourcecommunity-hub/join-the-community#80]
**Name: ANDRI HU** 
**Location: Javanesse Indonesia** 
**Interest: Singapore **

### Why do you want to join?
> I want to join because , Im need to join our community to make a good code review / security research.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@imhunterand Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
