### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by VasuDevrani** [opensourcecommunity-hub/join-the-community#81]
**Name:** Vasu Devrani
**Location:** Delhi, India
**Discord username(optional):-** Si-vasu

### Why do you want to join?
> I want to join because I love to help out others and contribute

**Comment by Susmita-Dey** [comment]
@VasuDevrani Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
