### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by rohitverse** [opensourcecommunity-hub/join-the-community#82]
**Name: Rohit Kumar** 
**Location: Jalandhar** 
**Interest: Blockchain Development**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to contribute in open source & contribute to Coding community with my knowledge that can be very helpful for others

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@rohitverse Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
