### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by cemmanuelonyema** [opensourcecommunity-hub/join-the-community#83]
**Emmanuel Onyema:** 
**Nigeria:** 
**Open source, Blockchain, front-end development:**
**Discord: ceonyema#0956:-**

### Why do you want to join?
> I want to join because I'm interested in open source and would like to be part of the community.

**Comment by Susmita-Dey** [comment]
@cemmanuelonyema Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
