### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by prakhartiwari0** [opensourcecommunity-hub/join-the-community#85]
**Name:** Prakhar Tiwari
**Location:** Uttar Pradesh, India 
**Interest:** Science and Technology
**Discord username(optional):-** Prakhar#7828

### Why do you want to join?
> I want to join because I want to connect with people and collaborate with them. I am interested in Open Source.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@prakhartiwari0 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
