### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by sudochain** [opensourcecommunity-hub/join-the-community#86]
**Name:sudochain** 
**Location:india** 
**Interest:coding**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because i want to contribute in open source community

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@sudochain Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
