### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by tatticoder** [opensourcecommunity-hub/join-the-community#87]
**Name:**  Naman
**Location:** India
**Interest:** Web development and DevOps
**Discord username(optional):-**

### Why do you want to join?
> I want to join because i am getting started in tech world and I would like to be a part of supportive and nurturing community that would help me grow.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@tatticoder Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
