### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by samuelbarrionuevo** [opensourcecommunity-hub/join-the-community#89]
**Name:Eric Samuel Barrionuevo** 
**Location:Buenos Aires Argentina** 
**Interest:Languages programming: C#, javascript, php, java**
*:-**

### Why do you want to join?
> I want to join because i want colaborate into the projects community

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@samuelbarrionuevo Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
