### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by sundaramawasthi** [opensourcecommunity-hub/join-the-community#9]
**Name:** 
Sundram Awasthi
**Location:** 
Lucknow ,India
**Interest:**
DevOPS , open source contribuation
**Discord username(optional):-**

### Why do you want to join?
> I want to join because 
I want to join this commnuity because i want to contribuate and help to grow commnuity

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
Welcome to the community!!! Thanks for creating this issue. Invitation has been sent to you. Accept it and make your membership public.
