### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Rushijaviya** [opensourcecommunity-hub/join-the-community#90]
**Name:** Rushi Javiya
**Location:** Gujarat
**Interest:** Back-end development
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to grow by contributing to the community. 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Rushijaviya Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
