### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by AvidCoder101** [opensourcecommunity-hub/join-the-community#91]
**Name: Avid Coder** 
**Location: -** 
**Interest: Html, js, css, node, react**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I'd like to contribute

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@AvidCoder101 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
