### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by ctiptopper** [opensourcecommunity-hub/join-the-community#92]
Tom Ford 
California

 Why do you want to join?
 I want to join because I like this organization

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by ctiptopper** [comment]
I want to join this organization. 
How can I join ?

**Comment by Susmita-Dey** [comment]
@ctiptopper Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
