### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by abitsalihu** [opensourcecommunity-hub/join-the-community#93]
**Name: Abit Salihu** 
**Location: Prishtine/Kosova** 
**Interests: Front End Development / Football**
**Discord username(optional): hellzjackazz#2972**

### Why do you want to join?
> I want to join because I am currently learning Front End Development and through my journey I would love to help other people with their open source projects.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@abitsalihu Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
