### ISSUE TITLE
Pls Review my Profile ♟

### ISSUE THREAD

**Issue by RajarshiCode** [opensourcecommunity-hub/join-the-community#99]
### GitHub Profile Link:- 
`https://github.com/RajarshiCode`

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub)

**Comment by Susmita-Dey** [comment]
Hey @RajarshiCode 

Make the following improvements:
- Translate Bengali lines into English
- Keep things in center
- You can align some items side by side to remove the extra space in the right
- Viewers and Followers Count part is extra; you can remove it
- If you're adding banner at the top, then remove one or two graphs to keep your profile of medium size.

**Comment by RajarshiCode** [comment]
THANK YOU SO MUCH!
